apiVersion: cache.example.com/v1alpha1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: memcached-operator
    app.kubernetes.io/managed-by: kustomize
  name: redis-sample-no-password
  namespace: memcached-operator-system
spec:
  size: 2
  containerPort: 6379 